development: 
  adapter: postgresql
  encoding: unicode
  database: beltexam_development
  pool: 5
  username: ubuntu
  password: 

test: 
  adapter: postgresql
  encoding: unicode
  database: beltexam_test
  pool: 5
  username: ubuntu
  password: 

production: 
  adapter: postgresql
  encoding: unicode
  database: beltexam_production
  pool: 5
  username: ubuntu
  password: